[[redirects]]
  from = "https://sparkly-moonbeam-be963d.netlify.app"
  to = "https://clinic-backend-xavv.onrender.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
